# Develop override settings

url: http://localhost:4000

chatbot:
  enabled: true
  endpoint: "http://127.0.0.1:8787/api/chat"

contact_form:
  enabled: true
  endpoint: "http://127.0.0.1:8787/api/contact"

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
