services:
  caddy:
    networks:
      default: {}
      intranet_edge: {}
      ab_test_private: {}
      classroom_picker_private: {}

networks:
  intranet_edge:
    external: true
    name: ximarketing_intranet_edge
  ab_test_private:
    external: true
    name: ximarketing_ab_test_private
  classroom_picker_private:
    external: true
    name: ximarketing_classroom_picker_private
